version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27020:27017"
      - "27021:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1

volumes:
   mongodata:

networks:
   network1: